import { Project } from "./ProjectTypes";

const projects: Project[] = [
  {
    id: "1",
    title: "SIAKAD",
    description: "Membuat aplikasi sistem informasi akademik (SIAKAD)...",
    category: "Web Development",
    tags: ["Laravel", "Tailwind", "MySQL"],
    image: "/project/siakad.png",
    githubUrl: "#",
    date: "2024-06-20",
    featured: true,
  },
  {
    id: "2",
    title: "Ecc Dentch",
    description: "Website Survei Gigi adalah platform digital...",
    category: "Web Development",
    tags: ["Laravel", "Tailwind", "MySQL"],
    image: "/project/gigi.png",
    githubUrl: "#",
    date: "2024-11-21",
    featured: true,
  },
  {
    id: "3",
    title: "DarkMoon",
    description: "Website ecommerce DarkMoon adalah website yang dirancang...",
    category: "Frontend Development",
    tags: ["React", "Tailwind", "Frammer"],
    image: "/project/ecommerce.png",
    githubUrl: "#",
    date: "2024-09-15",
    featured: true,
  },
  {
    id: "4",
    title: "Sosmed",
    description: "Aplikasi ini merupakan aplikasi sosial media...",
    category: "Web Development",
    tags: ["Laravel", "Tailwind", "MySQL"],
    image: "/project/sosmed.png",
    githubUrl: "#",
    date: "2024-05-12",
    featured: true,
  },
  {
    id: "5",
    title: "Shanum Bakery",
    description: "Website Shanum Bakery adalah sebuah landing page...",
    category: "Frontend Development",
    tags: ["React", "Tailwind", "Frammer"],
    image: "/project/shanum.png",
    githubUrl: "#",
    date: "2025-01-12",
    featured: true,
  },
  {
    id: "6",
    title: "Kennedy Classifier",
    description: "Website Kennedy Classifier adalah website edukasi gigi...",
    category: "Web Development",
    tags: ["React", "Tailwind", "TypeScript", "ExpressJs", "PostgreSQL", "Frammer"],
    image: "/project/kennedy.png",
    githubUrl: "#",
    date: "2025-07-15",
    featured: true,
  },
];

export default projects;
